-- Custom SQL migration file, put you code below! --
ALTER TABLE "conversation_states" DROP CONSTRAINT "chk_conversation_state";
ALTER TABLE "conversation_states" ADD CONSTRAINT "chk_conversation_state" CHECK ("current_state" IN ('IDLE','ONBOARDING_START','ONBOARDING_DRIVE','ONBOARDING_FILE','ONBOARDING_SHEET','ONBOARDING_VALIDATING_ACCESS','ONBOARDING_MAPPING','ONBOARDING_CATEGORIES','EXPENSE_RECEIVING','EXPENSE_CLARIFYING','EXPENSE_REVIEW','EXPENSE_CORRECTING','EXPENSE_SAVING','EXPENSE_SAVING_RETRY','EXPENSE_UNDO_CONFIRMING'));
